name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      WEBHOOK_TOKEN: ${{ vars.COVERALLS }}

    steps:
    - name: Add mask
      id: mask
      run: |
        echo "::set-output name=coveralls, add-mask=true::${{ vars.COVERALLS }}"

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          6.0.x
          7.0.x

    - name: Run NUKE
      run: ./build.ps1
      env:
        NuGetApiKey: ${{ secrets.NUGETAPIKEY }}
        CoverallsToken: $WEBHOOK_TOKEN

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./Artifacts/*


  only-unit-tests:

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          6.0.x
          7.0.x

    - name: Run NUKE
      run: ./build.sh UnitTests
